### ISSUE TITLE
The example strategy in "Quickstart" document is not working

### ISSUE THREAD

**Issue by uuuzz** [nautechsystems/nautilus_trader#1432]
# Bug Report

### Expected Behavior
The example code in https://docs.nautilustrader.io/develop/getting_started/quickstart.html cannot work out-of-box with package installed. 

### Actual Behavior
When running the code I got the following error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[3], line 167
    163 from nautilus_trader.backtest.node import BacktestNode
    164 from nautilus_trader.backtest.results import BacktestResult
--> 167 node = BacktestNode(configs=[config])
    169  # Runs one or many configs synchronously
    170 results: list[BacktestResult] = node.run()

File /opt/homebrew/Caskroom/miniconda/base/envs/nautilus/lib/python3.10/site-packages/nautilus_trader/backtest/node.py:72, in BacktestNode.__init__(self, configs)
     66 PyCondition.not_empty(configs, "configs")
     67 PyCondition.true(
     68     all(isinstance(config, BacktestRunConfig) for config in configs),
     69     "configs",
     70 )
---> 72 self._validate_configs(configs)
     74 # Configuration
     75 self._configs: list[BacktestRunConfig] = configs

File /opt/homebrew/Caskroom/miniconda/base/envs/nautilus/lib/python3.10/site-packages/nautilus_trader/backtest/node.py:169, in BacktestNode._validate_configs(self, configs)
    164         raise InvalidConfiguration(
    165             f"`end_time` ({data_config.end_time}) is before `start_time` ({data_config.start_time})",
    166         )
    168 instrument_id: InstrumentId = data_config.instrument_id
--> 169 if instrument_id.venue not in venue_ids:
    170     raise InvalidConfiguration(
    171         f"Venue '{instrument_id.venue}' for {instrument_id} "
    172         f"does not have a `BacktestVenueConfig`",
    173     )

AttributeError: 'str' object has no attribute 'venue'
```

### Steps to Reproduce the Problem

1. Follow the Quickstart to download sample data
2. create a python file `main.py` and copy all python code inside the quick start to main.py
3. execute the python file: `python main.py`

### Specifications

- OS platform: Mac 14.2.1, M3 chip
- Python version: 3.10
- `nautilus_trader` version: 1.182.0

**Comment by cjdsellers** [comment]
Hey @uuuzz 

Thanks for the report. I just pushed a fix for this to `develop` branch.

**Comment by giabaocorn20** [comment]
Hey there1

i encountered the same problem too! When I tried to run it on Google Colab, I got the same error 

```
AttributeError                          Traceback (most recent call last)
[<ipython-input-94-573917c04e17>](https://localhost:8080/#) in <cell line: 5>()
      3 
      4 
----> 5 node = BacktestNode(configs=[config])
      6 
      7  # Runs one or many configs synchronously

1 frames
[/usr/local/lib/python3.10/dist-packages/nautilus_trader/backtest/node.py](https://localhost:8080/#) in _validate_configs(self, configs)
    167 
    168                 instrument_id: InstrumentId = data_config.instrument_id
--> 169                 if instrument_id.venue not in venue_ids:
    170                     raise InvalidConfiguration(
    171                         f"Venue '{instrument_id.venue}' for {instrument_id} "

AttributeError: 'str' object has no attribute 'venue'
```

**Comment by cjdsellers** [comment]
Hi @giabaocorn20

Yes, unfortunately this issue will persist until the next release - which we should be able to get out very soon.

**Comment by JaydenElliott** [comment]
There have been some releases since this, however the issue is still present. Is there some work around we can use for now?

**Comment by cjdsellers** [comment]
Hi @JaydenElliott 

Yes, it has indeed been fixed. 

The issue was an instrument ID that was being defined as a string, instead of an `InstrumentId`, so I'd say what's happening here is your tutorial code still contains that error (this was an error in the tutorial, not the main package).

You could try running any of the examples found in the jupyterlab docker container:

```
docker pull ghcr.io/nautechsystems/jupyterlab:nightly --platform linux/amd64
docker run -p 8888:8888 ghcr.io/nautechsystems/jupyterlab:nightly
```

Or you could also checkout the tutorial again and compare the code you have looking for any differences, but this is probably the line you'd need to change:

```
engine = BacktestEngineConfig(
    strategies=[
        ImportableStrategyConfig(
            strategy_path="__main__:MACDStrategy",
            config_path="__main__:MACDConfig",
            config=dict(
              instrument_id=instruments[0].id,  # <--- Should be an instrument ID, not a string
              fast_period=12,
              slow_period=26,
            ),
        )
    ],
    logging=LoggingConfig(log_level="ERROR"),  # Lower to `INFO` to see more logging about orders, events, etc.
)
```

Hope that helps! let me know if you can get it working.
